# -*- coding: utf-8 -*-
"""FOCA - Anterior.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h8SXj54ICsp8_wQRA7WX-je_KSsyP9Gr
"""

from time import time
from matplotlib import pyplot as plt
import numpy as np

lista_n = [1000, 10000, 100000] #Número de iterações
t = []
R = 100
for n in lista_n:
    tt = []
    for r in range(R):
        tic = time()#tempo antes
        for i in range(n):
            x = 1
        toc = time()#tempo depois
        tt.append((toc - tic)/n)
    t.append(tt)

    #saída
    #print(f'n:{n} tempo:{t[-1]:f} segundos')
    bins = 50
    plt.hist(tt)
    plt.title(f"n = {n}")
    plt.savefig(f"tempos_n{n}.png")
    plt.show()

    # determinar valor corte para cada n
    # filtrar tt: tt.filter = (tt < t)
    # calcular: média: np.mean(tt.filter)
    # Focalaço = (0, n + 1, n +1, n + 5)
    # Foca = (0, n + 1, n + 1, n + 5 + n)